model:
  target: models.unet.UNetModelSwin_3d
  ckpt_path: weights/resshift_realsrx4_s15_v1.pth
  teacher_ckpt_path: weights/resshift_realsrx4_s15_v1.pth
  params:
    image_size: 64
    in_channels: 6
    model_channels: 160
    out_channels: 3
    cond_lq: True
    attention_resolutions: [64,32,16,8]
    dropout: 0
    channel_mult: [1, 2, 2, 4]
    num_res_blocks: [2, 2, 2, 2]
    conv_resample: True
    dims: 2
    use_fp16: False
    num_head_channels: 32
    use_scale_shift_norm: True
    resblock_updown: False
    swin_depth: 2
    swin_embed_dim: 192
    window_size: 8
    mlp_ratio: 4

diffusion:
  target: models.script_util.create_gaussian_diffusion_3d
  params:
    sf: 4
    schedule_name: exponential
    schedule_kwargs:
      power: 0.3
    etas_end: 0.99
    steps: 15
    min_noise_level: 0.04
    kappa: 2.0
    weighted_mse: False
    predict_type: xstart
    timestep_respacing: ~
    scale_factor: 1.0
    normalize_input: True
    latent_flag: True

autoencoder:
  target: ldm.models.autoencoder.VQModelTorch
  ckpt_path: weights/autoencoder_vq_f4.pth
  use_fp16: True
  params:
    embed_dim: 3
    n_embed: 8192
    ddconfig:
      double_z: False
      z_channels: 3
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions: []
      dropout: 0.0
      padding_mode: zeros

degradation:
  sf: 4
  # the first degradation process
  resize_prob: [0.2, 0.7, 0.1]  # up, down, keep
  resize_range: [0.15, 1.5]
  gaussian_noise_prob: 0.5
  noise_range: [1, 30]
  poisson_scale_range: [0.05, 3.0]
  gray_noise_prob: 0.4
  jpeg_range: [30, 95]

  # the second degradation process
  second_order_prob: 0.0 ### 0.5
  second_blur_prob: 0.8
  resize_prob2: [0.3, 0.4, 0.3]  # up, down, keep
  resize_range2: [0.3, 1.2]
  gaussian_noise_prob2: 0.5
  noise_range2: [1, 25]
  poisson_scale_range2: [0.05, 2.5]
  gray_noise_prob2: 0.4
  jpeg_range2: [30, 95]

  gt_size: 256 
  resize_back: False
  use_sharp: False

data:
  train:
    type: realesrgan_master_3d
    params:
      root_path: '/content'
      dir_paths: []
      realesrgan_cardiac_bowl_3d:
        txt_file_path:  [
                          'traindata/train_cardiac_bowl_3d.txt', 
                          #'traindata/ffhq256.txt',
                        ] 
      realesrgan_SurgT:
        txt_file_path:  [
                          'traindata/train_SurgT.txt', 
                          #'traindata/ffhq256.txt',
                        ] 
      im_exts: ['JPEG', ]
      io_backend:
        type: disk
      blur_kernel_size: 21
      kernel_list: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob: 0.1
      blur_sigma: [0.2, 3.0]
      betag_range: [0.5, 4.0]
      betap_range: [1, 2.0]

      blur_kernel_size2: 15
      kernel_list2: ['iso', 'aniso', 'generalized_iso', 'generalized_aniso', 'plateau_iso', 'plateau_aniso']
      kernel_prob2: [0.45, 0.25, 0.12, 0.03, 0.12, 0.03]
      sinc_prob2: 0.1
      blur_sigma2: [0.2, 1.5]
      betag_range2: [0.5, 4.0]
      betap_range2: [1, 2.0]

      final_sinc_prob: 0.8

      gt_size: 256
      crop_pad_size: 300
      use_hflip: True
      use_rot: False
      rescale_gt: True
  val:
    type: tempoSpatial_master_3d #folder
    params:
      sf: 4
      root_path: '/content'
      #dir_path: testdata/RealSet128/
      #dir_path_extra: ~
      dir_paths: []
      tempoSpatial_cardiac_bowl_3d:
        txt_file_path:  [
                          'testdata/test_mini_cardiac_bowl_3d.txt', 
                        ] 
      tempoSpatial_SurgT:
        txt_file_path:  [
                          'testdata/test_SurgT_mini.txt',
                        ]
      im_exts: ['JPEG', ]
      io_backend:
        type: disk
      transform_type: default
      transform_kwargs:
          mean: 0.5
          std: 0.5
      gt_size: 256
      rescale_gt: True
      resize_back: False
      matlab_mode: False
    

train:
  learn_xT: True
  finetune_use_gt: 1.
  # xT_cov_loss: 0.1

  lr: 5e-5
  batch: [112, 8] #[176, 8] #[384, 8] #[64, 8]  #batchsize for training and validation
  use_fp16: False
  microbatch: 28 #44
  seed: 123456
  global_seeding: False
  prefetch_factor: 2 #4
  num_workers: 2 #2 #8 #16
  ema_rate: 0.999
  iterations: 500000
  milestones: [1000, 50000] ###[5000, 500000]
  weight_decay: 0
  save_freq: 1000 # model(s) save freq.
  # val_freq:  10000
  # log_freq: [1000, 5000, 1] #[training loss, training images, val images]
  val_freq:  1000 #1000
  log_freq: [10, 5000, 5] #[training loss, training images, val images]
  save_images: True  # save the images of tensorboard logging
  use_ema_val: True
  test_baseline: True

experiment_evaluate:
  save_images: True
  save_path: experiment_evaluate_cardiac_bowl_3d_esrgan
  batch: 4 #64
  prefetch_factor: 8
  num_workers: 12
